# Generated by Django 5.1.15 on 2026-04-12 21:51

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.profiles.models.avatar_upload_to)),
                ('header', models.ImageField(blank=True, upload_to=apps.profiles.models.header_upload_to)),
                ('website_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='actors.actor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
