# Generated by Django 5.1.15 on 2026-04-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_follower_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_following_count',
            field=models.BooleanField(default=True),
        ),
    ]
