# Generated by Django 5.1.15 on 2026-04-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_show_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private_account',
            field=models.BooleanField(default=False),
        ),
    ]
