# Generated by Django 5.1.15 on 2026-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profileedithistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_reveal_spoilers",
            field=models.BooleanField(default=False),
        ),
    ]
