# Generated by Django 5.1.15 on 2026-04-19 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_minor_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='parental_controls_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuardianEmailVerificationToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_email_tokens', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='profiles_gu_token_baaadb_idx'), models.Index(fields=['expires_at'], name='profiles_gu_expires_ad8b83_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentalControlChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_is_private_account', models.BooleanField(default=False)),
                ('proposed_auto_reveal_spoilers', models.BooleanField(default=False)),
                ('proposed_show_follower_count', models.BooleanField(default=True)),
                ('proposed_show_following_count', models.BooleanField(default=True)),
                ('proposed_is_minor_account', models.BooleanField(default=False)),
                ('proposed_parental_controls_enabled', models.BooleanField(default=False)),
                ('proposed_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_change_requests', to='profiles.profile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parental_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='profiles_pa_token_3d5f3e_idx'), models.Index(fields=['expires_at'], name='profiles_pa_expires_0df8fd_idx')],
            },
        ),
    ]
