# Generated by Django 5.1.15 on 2026-04-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_guardian_restrict_dms_to_teens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guardianmanagementaccesstoken',
            new_name='profiles_gu_token_f85727_idx',
            old_name='profiles_gua_token_5532bb_idx',
        ),
        migrations.RenameIndex(
            model_name='guardianmanagementaccesstoken',
            new_name='profiles_gu_expires_7e5c29_idx',
            old_name='profiles_gua_expire_5f13e5_idx',
        ),
        migrations.AddField(
            model_name='parentalcontrolchangerequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
