# Generated by Django 5.1.15 on 2026-05-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recoverycode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('view_support_user_info', 'Can view support-oriented user/account information'), ('resend_verification_email', 'Can resend user verification emails'), ('manage_account_lifecycle_support', 'Can issue account lifecycle support actions')]},
        ),
    ]
