# Generated by Django 5.1 on 2026-04-14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("conversation_type", models.CharField(choices=[("direct", "Direct"), ("group", "Group")], default="direct", max_length=16)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_conversations", to="actors.actor"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["conversation_type", "created_at"], name="private_mes_convers_204363_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserIdentityKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key_id", models.CharField(max_length=128, unique=True)),
                ("public_key", models.TextField()),
                ("algorithm", models.CharField(choices=[("ed25519", "Ed25519"), ("curve25519", "Curve25519")], default="ed25519", max_length=32)),
                ("fingerprint_hex", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="identity_keys", to="actors.actor")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["actor", "is_active"], name="private_mes_actor_i_901640_idx"), models.Index(fields=["fingerprint_hex"], name="private_mes_fingerp_5ce1af_idx")],
            },
        ),
        migrations.CreateModel(
            name="EncryptedMessageEnvelope",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ciphertext", models.TextField()),
                ("message_nonce", models.CharField(max_length=255)),
                ("sender_key_id", models.CharField(max_length=128)),
                ("recipient_key_id", models.CharField(max_length=128)),
                ("key_epoch", models.PositiveIntegerField(default=1)),
                ("aad_hash", models.CharField(blank=True, max_length=255)),
                ("encryption_scheme", models.CharField(choices=[("xchacha20poly1305", "XChaCha20-Poly1305")], default="xchacha20poly1305", max_length=32)),
                ("client_message_id", models.CharField(blank=True, max_length=128)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="private_messages.conversation")),
                (
                    "recipient_actor",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dm_received_messages", to="actors.actor"),
                ),
                (
                    "sender",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dm_sent_messages", to="actors.actor"),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["conversation", "created_at"], name="private_mes_convers_e762c5_idx"),
                    models.Index(fields=["recipient_actor", "created_at"], name="private_mes_recipie_58f366_idx"),
                    models.Index(fields=["sender", "created_at"], name="private_mes_sender__8a7fea_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=~models.Q(client_message_id=""), fields=("conversation", "sender", "client_message_id"), name="uniq_client_message_per_sender"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("participant_state", models.CharField(choices=[("active", "Active"), ("left", "Left"), ("removed", "Removed")], default="active", max_length=16)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dm_participations", to="actors.actor")),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="private_messages.conversation")),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["actor", "participant_state"], name="private_mes_actor_i_b1bb9f_idx"), models.Index(fields=["conversation", "participant_state"], name="private_mes_convers_798b9f_idx")],
                "constraints": [models.UniqueConstraint(fields=("conversation", "actor"), name="uniq_conversation_actor")],
            },
        ),
    ]
