# Generated by Django 5.1 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationparticipant",
            name="acknowledged_remote_key_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="acknowledged_remote_key_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
