# Generated by Django 5.1.15 on 2026-04-17 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('private_messages', '0003_conversationparticipant_last_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMRolloutPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('disabled', 'Disabled (Feature Flag Off)'), ('allowlist', 'Allowlist (Explicit Per-Actor)'), ('beta', 'Beta (Opt-In)'), ('general', 'General Availability')], default='disabled', max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Internal notes on rollout rationale and milestones')),
                ('allowlisted_actors', models.ManyToManyField(blank=True, help_text='Only applies when stage=ALLOWLIST', related_name='pm_allowlisted', to='actors.actor')),
            ],
            options={
                'verbose_name_plural': 'PM Rollout Policies',
                'abstract': False,
            },
        ),
    ]
