# Generated by Django 5.1.15 on 2026-04-17 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('private_messages', '0004_pmrolloutpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyLifecycleAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Key Created'), ('rotated', 'Key Rotated'), ('activated', 'Key Activated'), ('deactivated', 'Key Deactivated'), ('marked_compromised', 'Marked as Compromised'), ('unmarked_compromised', 'Compromise Mark Removed'), ('expired', 'Key Expired'), ('acknowledged', 'Key Acknowledged in Conversation')], max_length=32)),
                ('reason', models.TextField(blank=True, help_text='Reason for the event (e.g., rotation reason, compromise details)')),
                ('triggered_by', models.CharField(choices=[('user_action', 'User Action'), ('system', 'System'), ('abuse_detection', 'Abuse Detection')], default='user_action', max_length=64)),
                ('related_conversation_id', models.UUIDField(blank=True, help_text='Conversation ID if applicable', null=True)),
            ],
            options={
                'verbose_name_plural': 'Key Lifecycle Audit Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useridentitykey',
            name='compromised_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when compromise was detected', null=True),
        ),
        migrations.AddField(
            model_name='useridentitykey',
            name='compromised_reason',
            field=models.TextField(blank=True, help_text='Description of compromise reason/incident'),
        ),
        migrations.AddField(
            model_name='useridentitykey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Key expiration timestamp for auto-invalidation', null=True),
        ),
        migrations.AddField(
            model_name='useridentitykey',
            name='is_compromised',
            field=models.BooleanField(default=False, help_text='Mark as True if key is suspected compromised'),
        ),
        migrations.AddIndex(
            model_name='useridentitykey',
            index=models.Index(fields=['actor', 'is_compromised'], name='private_mes_actor_i_4165eb_idx'),
        ),
        migrations.AddField(
            model_name='keylifecycleauditlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_audit_logs', to='actors.actor'),
        ),
        migrations.AddField(
            model_name='keylifecycleauditlog',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='private_messages.useridentitykey'),
        ),
        migrations.AddIndex(
            model_name='keylifecycleauditlog',
            index=models.Index(fields=['actor', 'event_type', 'created_at'], name='private_mes_actor_i_dfc504_idx'),
        ),
        migrations.AddIndex(
            model_name='keylifecycleauditlog',
            index=models.Index(fields=['key', 'event_type'], name='private_mes_key_id_9429d2_idx'),
        ),
    ]
