# Generated by Django 5.1.15 on 2026-04-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0006_conversation_compromised_at_and_security_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='private_mes_comprom_a5090b_idx',
            old_name='idx_conversation_compromised',
        ),
        migrations.RenameIndex(
            model_name='useridentitykey',
            new_name='private_mes_actor_i_5bdcc0_idx',
            old_name='idx_useridentitykey_actor_revoked',
        ),
    ]
