# Generated by Django 5.1.15 on 2026-04-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0008_encryptedmessageattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='encryptedmessageattachment',
            new_name='private_mes_envelop_1ccaca_idx',
            old_name='private_mes_envelop_f4c77a_idx',
        ),
    ]
