# Generated by Django 5.1.15 on 2026-04-13 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('last_traceback', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task_name', 'status'], name='core_asynct_task_na_00a1d8_idx'), models.Index(fields=['correlation_id'], name='core_asynct_correla_5dda94_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_name', 'idempotency_key'), name='uniq_task_execution_key')],
            },
        ),
        migrations.CreateModel(
            name='AsyncTaskFailure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('max_retries', models.PositiveIntegerField(default=0)),
                ('is_terminal', models.BooleanField(default=False)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['task_name', 'is_terminal'], name='core_asynct_task_na_5c9cb0_idx'), models.Index(fields=['correlation_id'], name='core_asynct_correla_6d686e_idx')],
            },
        ),
    ]
