# Generated by Django 5.1.15 on 2026-04-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctaskfailure',
            name='terminal_reason',
            field=models.CharField(blank=True, choices=[('max_retries_exceeded', 'Max Retries Exceeded'), ('timeout', 'Timeout'), ('invalid_payload', 'Invalid Payload'), ('manual_dismiss', 'Manually Dismissed'), ('manual_replay', 'Manual Replay'), ('other', 'Other')], help_text='Reason why task became terminal (Phase 7.2)', max_length=32),
        ),
        migrations.AddIndex(
            model_name='asynctaskfailure',
            index=models.Index(fields=['is_terminal', 'terminal_reason', 'created_at'], name='core_asynct_is_term_fda5f3_idx'),
        ),
    ]
