# Generated by Django 5.1.15 on 2026-05-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asynctaskfailure_terminal_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctaskexecution',
            options={'permissions': [('view_support_diagnostics', 'Can view support diagnostics'), ('view_security_posture', 'Can view security posture dashboards'), ('run_email_diagnostics', 'Can run email diagnostics')]},
        ),
    ]
