# Generated by Django 5.1.15 on 2026-04-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing (Legacy)'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='open', max_length=16),
        ),
    ]
