# Generated by Django 5.1.15 on 2026-04-13 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('moderation', '0002_alter_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('login_anomaly', 'Login Anomaly'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('email_verification', 'Email Verification'), ('email_changed', 'Email Changed'), ('moderator_privilege_grant', 'Moderator Privilege Grant'), ('moderator_privilege_revoke', 'Moderator Privilege Revoke'), ('moderation_action_create', 'Moderation Action Created')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='moderation__user_id_542f03_idx'), models.Index(fields=['event_type', '-created_at'], name='moderation__event_t_c3eac4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustSignal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_age_days', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('recent_reports_count', models.IntegerField(default=0)),
                ('recent_actions_count', models.IntegerField(default=0)),
                ('posts_last_hour', models.IntegerField(default=0)),
                ('follows_last_hour', models.IntegerField(default=0)),
                ('likes_last_hour', models.IntegerField(default=0)),
                ('reposts_last_hour', models.IntegerField(default=0)),
                ('trust_score', models.IntegerField(default=50)),
                ('is_throttled', models.BooleanField(default=False)),
                ('throttle_reason', models.CharField(blank=True, max_length=64)),
                ('throttled_until', models.DateTimeField(blank=True, null=True)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_signal', to='actors.actor')),
            ],
            options={
                'ordering': ['-last_computed_at'],
                'indexes': [models.Index(fields=['is_throttled', '-last_computed_at'], name='moderation__is_thro_48f53f_idx')],
            },
        ),
    ]
