# Generated by Django 5.1.15 on 2026-04-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_securityauditevent_trustsignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
