# Generated by Django 5.1 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0004_alter_securityauditevent_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("dmca_ip", "DMCA / IP Complaint"),
                    ("minor_safety", "Posting of a Minor"),
                    ("graphic_death_injury", "Death or Severe Injury Content"),
                    ("non_consensual_intimate_media", "Non-Consensual Intimate Media"),
                    ("impersonation", "Impersonation"),
                    ("harassment", "Harassment"),
                    ("spam_scam", "Spam / Scam"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=128,
            ),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE moderation_report
            SET reason = CASE reason
                WHEN 'spam' THEN 'spam_scam'
                WHEN 'scam' THEN 'spam_scam'
                WHEN 'abuse' THEN 'harassment'
                WHEN 'user_report' THEN 'other'
                WHEN 'unspecified' THEN 'other'
                ELSE reason
            END,
            severity = CASE reason
                WHEN 'minor_safety' THEN 'critical'
                WHEN 'non_consensual_intimate_media' THEN 'critical'
                WHEN 'dmca_ip' THEN 'high'
                WHEN 'graphic_death_injury' THEN 'high'
                WHEN 'impersonation' THEN 'high'
                WHEN 'abuse' THEN 'medium'
                WHEN 'harassment' THEN 'medium'
                WHEN 'spam' THEN 'low'
                WHEN 'scam' THEN 'low'
                WHEN 'spam_scam' THEN 'low'
                ELSE 'medium'
            END
            """,
            reverse_sql="UPDATE moderation_report SET severity = 'medium'",
        ),
    ]