# Generated by Django 5.1.15 on 2026-04-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_report_assigned_to_report_evidence_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('login_anomaly', 'Login Anomaly'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('email_verification', 'Email Verification'), ('email_changed', 'Email Changed'), ('moderator_privilege_grant', 'Moderator Privilege Grant'), ('moderator_privilege_revoke', 'Moderator Privilege Revoke'), ('moderation_action_create', 'Moderation Action Created'), ('abuse_auto_action', 'Abuse Auto Action')], max_length=32),
        ),
    ]
