# Generated by Django 5.1.15 on 2026-05-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_alter_securityauditevent_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('access_moderation_dashboard', 'Can access the moderation dashboard'), ('review_reports', 'Can review moderation reports'), ('manage_moderation_actions', 'Can apply moderation actions'), ('view_audit_summary', 'Can view moderation audit summaries')]},
        ),
        migrations.AlterModelOptions(
            name='securityauditevent',
            options={'ordering': ['-created_at'], 'permissions': [('view_security_audit_events', 'Can review security audit events')]},
        ),
        migrations.AlterModelOptions(
            name='trustsignal',
            options={'ordering': ['-last_computed_at'], 'permissions': [('manage_trust_signals', 'Can review and manage trust signals')]},
        ),
    ]
