# Generated by Django 5.1.15 on 2026-04-12 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('software_name', models.CharField(blank=True, max_length=100)),
                ('software_version', models.CharField(blank=True, max_length=100)),
                ('is_blocked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='FederationObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_uri', models.URLField(max_length=500, unique=True)),
                ('external_id', models.CharField(max_length=500, unique=True)),
                ('object_type', models.CharField(choices=[('actor', 'Actor'), ('post', 'Post'), ('other', 'Other')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_metadata', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('processing_state', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('failed', 'Failed')], default='new', max_length=16)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='federation.instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FederationDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_uri', models.URLField(max_length=500)),
                ('activity_payload', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_deliveries', to='actors.actor')),
                ('target_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='federation.instance')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'retry_count'], name='federation__state_d20e35_idx')],
            },
        ),
    ]
