# Generated by Django 5.1.15 on 2026-04-17 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_instances_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instance',
            name='allowlist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='allowlist_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('blocked', 'Blocked')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='RemoteActor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('canonical_uri', models.URLField(max_length=500, unique=True)),
                ('public_key', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_actors', to='federation.instance')),
            ],
        ),
        migrations.CreateModel(
            name='RemotePost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_uri', models.URLField(max_length=500, unique=True)),
                ('content', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_posts', to='federation.instance')),
                ('remote_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='federation.remoteactor')),
            ],
        ),
        migrations.AddIndex(
            model_name='remoteactor',
            index=models.Index(fields=['instance', 'handle'], name='federation__instanc_650131_idx'),
        ),
        migrations.AddIndex(
            model_name='remotepost',
            index=models.Index(fields=['instance', 'remote_actor', 'created_at'], name='federation__instanc_88db18_idx'),
        ),
    ]
