# Generated by Django 5.1.15 on 2026-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_instance_added_by_instance_allowlist_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['domain'], 'permissions': [('manage_federation_allowlist', 'Can manage federation instance allowlist and blocking'), ('view_federation_health', 'Can view federation delivery health and instance stats')]},
        ),
    ]
