# Generated by Django 5.1.15 on 2026-04-12 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], default='local', max_length=16)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted'), ('remote', 'Remote')], default='active', max_length=16)),
                ('handle', models.CharField(max_length=128, unique=True)),
                ('canonical_uri', models.URLField(max_length=500, unique=True)),
                ('local_username', models.CharField(blank=True, max_length=30)),
                ('remote_domain', models.CharField(blank=True, max_length=255)),
                ('inbox_url', models.URLField(blank=True, max_length=500)),
                ('outbox_url', models.URLField(blank=True, max_length=500)),
                ('shared_inbox_url', models.URLField(blank=True, max_length=500)),
                ('remote_document', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_type', 'state'], name='actors_acto_actor_t_c2396b_idx'), models.Index(fields=['remote_domain'], name='actors_acto_remote__ea9ea1_idx')],
            },
        ),
    ]
