# Generated by Django 5.1.15 on 2026-04-19 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='handle_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='verified_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['is_verified', 'handle_locked'], name='actors_acto_is_veri_6b92a3_idx'),
        ),
    ]
