# Generated by Django 5.1.15 on 2026-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_handle_locked_actor_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['-created_at'], 'permissions': [('manage_actor_verification', 'Can grant or revoke actor verified status'), ('suspend_actor', 'Can suspend or unsuspend actor accounts')]},
        ),
    ]
