# Generated by Django 5.1.15 on 2026-04-12 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='actors.actor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='posts.post')),
            ],
            options={
                'ordering': ['-inserted_at'],
                'unique_together': {('owner', 'post')},
            },
        ),
    ]
