# Generated by Django 5.1.15 on 2026-04-13 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_is_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEditHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_content', models.TextField()),
                ('new_content', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='posts.comment')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_comments_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostEditHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_content', models.TextField(blank=True)),
                ('new_content', models.TextField(blank=True)),
                ('previous_spoiler_text', models.CharField(blank=True, max_length=255)),
                ('new_spoiler_text', models.CharField(blank=True, max_length=255)),
                ('previous_visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers_only', 'Followers Only'), ('private', 'Private')], max_length=24)),
                ('new_visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers_only', 'Followers Only'), ('private', 'Private')], max_length=24)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_posts_history', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
