# Generated by Django 5.1.15 on 2026-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentedithistory_postedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='is_18plus',
            field=models.BooleanField(default=False, help_text='Mark as 18+ content (adult themes).'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Mark as Not Safe For Work (sexual/graphic content).'),
        ),
    ]
