# Generated by Django 5.1.15 on 2026-04-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_nsfw_18plus_attachment_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
