# Generated by Django 5.1.15 on 2026-04-16 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_allow_media_only_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('embed_html', models.TextField(blank=True)),
                ('fetch_error', models.CharField(blank=True, max_length=500)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_preview', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='posts_linkp_post_id_40d527_idx')],
            },
        ),
    ]
