# Generated by Django 5.1.15 on 2026-04-18 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_link_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
        migrations.CreateModel(
            name="PostHashtag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "hashtag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post_hashtags", to="posts.hashtag"),
                ),
                (
                    "post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post_hashtags", to="posts.post"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(blank=True, related_name="posts", through="posts.PostHashtag", to="posts.hashtag"),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(fields=["tag"], name="posts_hasht_tag_8a3530_idx"),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(fields=["hashtag", "post"], name="posts_posth_hashtag_5f2898_idx"),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(fields=["post", "hashtag"], name="posts_posth_post_id_946f63_idx"),
        ),
        migrations.AddConstraint(
            model_name="posthashtag",
            constraint=models.UniqueConstraint(fields=("post", "hashtag"), name="posts_posthashtag_unique_post_tag"),
        ),
    ]
