# Generated by Django 5.1.15 on 2026-04-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_hashtag_indexing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hashtag',
            new_name='posts_hasht_tag_7a6858_idx',
            old_name='posts_hasht_tag_8a3530_idx',
        ),
        migrations.RenameIndex(
            model_name='posthashtag',
            new_name='posts_posth_hashtag_4777f7_idx',
            old_name='posts_posth_hashtag_5f2898_idx',
        ),
        migrations.RenameIndex(
            model_name='posthashtag',
            new_name='posts_posth_post_id_cf2f78_idx',
            old_name='posts_posth_post_id_946f63_idx',
        ),
    ]
