# Generated by Django 5.1.15 on 2026-04-22 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dislike",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "actor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dislikes", to="actors.actor"),
                ),
                (
                    "post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dislikes", to="posts.post"),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("actor", "post"), name="uniq_dislike")],
            },
        ),
    ]
