# Generated by Django 5.1.1 on 2026-04-25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_is_16plus"),
        ("social", "0002_dislike"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hidden_posts", to="actors.actor")),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hidden_by", to="posts.post")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("actor", "post"), name="uniq_hidden_post")],
            },
        ),
    ]
